// ─── Pre-built Product Catalog ───────────────────────────────────────────────
// Common food products for restaurant/cafe kitchen

export const PRODUCT_CATALOG = [
  // ── Мясо и птица ──
  { name: "Говядина (вырезка)", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Говядина (лопатка)", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Говядина (фарш)", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Свинина (корейка)", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Свинина (фарш)", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Баранина", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Курица (тушка)", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Куриное филе", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Куриные бёдра", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Куриные крылья", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Куриный фарш", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Индейка (филе)", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Печень куриная", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Печень говяжья", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Колбаса варёная", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },
  { name: "Сосиски", unit: "кг", nomType: "tovar", folder: "Мясо и птица" },

  // ── Рыба и морепродукты ──
  { name: "Сёмга (филе)", unit: "кг", nomType: "tovar", folder: "Рыба и морепродукты" },
  { name: "Форель", unit: "кг", nomType: "tovar", folder: "Рыба и морепродукты" },
  { name: "Минтай (филе)", unit: "кг", nomType: "tovar", folder: "Рыба и морепродукты" },
  { name: "Тилапия (филе)", unit: "кг", nomType: "tovar", folder: "Рыба и морепродукты" },
  { name: "Креветки", unit: "кг", nomType: "tovar", folder: "Рыба и морепродукты" },
  { name: "Кальмар", unit: "кг", nomType: "tovar", folder: "Рыба и морепродукты" },
  { name: "Тунец (консерв.)", unit: "шт", nomType: "tovar", folder: "Рыба и морепродукты" },

  // ── Овощи ──
  { name: "Картофель", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Морковь", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Лук репчатый", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Лук зелёный", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Чеснок", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Помидоры", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Огурцы", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Перец болгарский", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Перец чили", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Капуста белокочанная", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Капуста пекинская", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Капуста цветная", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Брокколи", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Баклажан", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Кабачок / цуккини", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Свёкла", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Редис", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Тыква", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Шпинат", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Салат (листовой)", unit: "кг", nomType: "tovar", folder: "Овощи" },
  { name: "Кукуруза (консерв.)", unit: "шт", nomType: "tovar", folder: "Овощи" },
  { name: "Горошек зелёный (консерв.)", unit: "шт", nomType: "tovar", folder: "Овощи" },
  { name: "Фасоль (консерв.)", unit: "шт", nomType: "tovar", folder: "Овощи" },
  { name: "Грибы шампиньоны", unit: "кг", nomType: "tovar", folder: "Овощи" },

  // ── Фрукты ──
  { name: "Яблоки", unit: "кг", nomType: "tovar", folder: "Фрукты" },
  { name: "Бананы", unit: "кг", nomType: "tovar", folder: "Фрукты" },
  { name: "Лимон", unit: "кг", nomType: "tovar", folder: "Фрукты" },
  { name: "Апельсин", unit: "кг", nomType: "tovar", folder: "Фрукты" },
  { name: "Клубника", unit: "кг", nomType: "tovar", folder: "Фрукты" },
  { name: "Виноград", unit: "кг", nomType: "tovar", folder: "Фрукты" },

  // ── Молочные продукты ──
  { name: "Молоко 3.2%", unit: "л", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Сливки 10%", unit: "л", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Сливки 33%", unit: "л", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Сметана 20%", unit: "кг", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Творог 9%", unit: "кг", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Масло сливочное 82%", unit: "кг", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Сыр твёрдый", unit: "кг", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Сыр моцарелла", unit: "кг", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Сыр пармезан", unit: "кг", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Сыр плавленый", unit: "кг", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Кефир", unit: "л", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Йогурт натуральный", unit: "кг", nomType: "tovar", folder: "Молочные продукты" },
  { name: "Яйцо куриное С1", unit: "шт", nomType: "tovar", folder: "Молочные продукты" },

  // ── Крупы, макароны, мука ──
  { name: "Мука пшеничная в/с", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Рис круглозёрный", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Рис длиннозёрный", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Гречка", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Овсянка (хлопья)", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Манная крупа", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Макароны (спагетти)", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Макароны (пенне)", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Лапша (лагман)", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Панировочные сухари", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Крахмал картофельный", unit: "кг", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Хлеб белый", unit: "шт", nomType: "tovar", folder: "Крупы и мука" },
  { name: "Лаваш", unit: "шт", nomType: "tovar", folder: "Крупы и мука" },

  // ── Масла и соусы ──
  { name: "Масло подсолнечное", unit: "л", nomType: "tovar", folder: "Масла и соусы" },
  { name: "Масло оливковое", unit: "л", nomType: "tovar", folder: "Масла и соусы" },
  { name: "Масло кунжутное", unit: "л", nomType: "tovar", folder: "Масла и соусы" },
  { name: "Уксус 9%", unit: "л", nomType: "tovar", folder: "Масла и соусы" },
  { name: "Соевый соус", unit: "л", nomType: "tovar", folder: "Масла и соусы" },
  { name: "Томатная паста", unit: "кг", nomType: "tovar", folder: "Масла и соусы" },
  { name: "Кетчуп", unit: "кг", nomType: "tovar", folder: "Масла и соусы" },
  { name: "Майонез", unit: "кг", nomType: "tovar", folder: "Масла и соусы" },
  { name: "Горчица", unit: "кг", nomType: "tovar", folder: "Масла и соусы" },

  // ── Специи и приправы ──
  { name: "Соль", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Перец чёрный молотый", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Перец красный молотый", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Зира (кумин)", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Куркума", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Паприка", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Корица", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Лавровый лист", unit: "г", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Укроп (свежий)", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Петрушка (свежая)", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Кинза (свежая)", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Базилик (свежий)", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Имбирь", unit: "кг", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Ванилин", unit: "г", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Разрыхлитель", unit: "г", nomType: "tovar", folder: "Специи и приправы" },
  { name: "Дрожжи сухие", unit: "г", nomType: "tovar", folder: "Специи и приправы" },

  // ── Сахар, мёд, сладости ──
  { name: "Сахар белый", unit: "кг", nomType: "tovar", folder: "Сахар и сладкое" },
  { name: "Сахарная пудра", unit: "кг", nomType: "tovar", folder: "Сахар и сладкое" },
  { name: "Мёд", unit: "кг", nomType: "tovar", folder: "Сахар и сладкое" },
  { name: "Какао-порошок", unit: "кг", nomType: "tovar", folder: "Сахар и сладкое" },
  { name: "Шоколад тёмный", unit: "кг", nomType: "tovar", folder: "Сахар и сладкое" },
  { name: "Шоколад молочный", unit: "кг", nomType: "tovar", folder: "Сахар и сладкое" },
  { name: "Сгущённое молоко", unit: "кг", nomType: "tovar", folder: "Сахар и сладкое" },
  { name: "Желатин", unit: "г", nomType: "tovar", folder: "Сахар и сладкое" },

  // ── Напитки ──
  { name: "Чай чёрный", unit: "кг", nomType: "tovar", folder: "Напитки" },
  { name: "Чай зелёный", unit: "кг", nomType: "tovar", folder: "Напитки" },
  { name: "Кофе молотый", unit: "кг", nomType: "tovar", folder: "Напитки" },
  { name: "Вода минеральная", unit: "л", nomType: "tovar", folder: "Напитки" },
];

// ─── Pre-built Dish Templates ────────────────────────────────────────────────
export const DISH_CATALOG = [
  // ── Ўзбек таомлари ──
  { name: "Плов (Ош)", category: "Ўзбек таомлари", outputUnit: "порц", outputQty: 10,
    steps: [
      { name: "Зирвак тайёрлаш", process: "Жарка", params: { temp: "180", time: "40" },
        ings: ["Масло подсолнечное", "Лук репчатый", "Морковь", "Говядина (лопатка)", "Соль", "Зира (кумин)"] },
      { name: "Гуруч пишириш", process: "Варка", params: { temp: "100", time: "30" },
        ings: ["Рис длиннозёрный"] },
    ]},
  { name: "Лагман", category: "Ўзбек таомлари", outputUnit: "порц", outputQty: 8,
    steps: [
      { name: "Ваджа тайёрлаш", process: "Тушение", params: { temp: "160", time: "35" },
        ings: ["Говядина (лопатка)", "Масло подсолнечное", "Лук репчатый", "Морковь", "Перец болгарский", "Помидоры", "Чеснок", "Томатная паста"] },
      { name: "Лапша пишириш", process: "Варка", params: { temp: "100", time: "10" },
        ings: ["Лапша (лагман)"] },
    ]},
  { name: "Шурпа", category: "Ўзбек таомлари", outputUnit: "порц", outputQty: 8,
    steps: [
      { name: "Гўшт қайнатиш", process: "Варка", params: { temp: "100", time: "90" },
        ings: ["Баранина", "Картофель", "Морковь", "Лук репчатый", "Помидоры", "Перец болгарский", "Соль", "Зира (кумин)"] },
    ]},
  { name: "Манты", category: "Ўзбек таомлари", outputUnit: "порц", outputQty: 10,
    steps: [
      { name: "Хамир тайёрлаш", process: "Смешивание", params: { time: "20" },
        ings: ["Мука пшеничная в/с", "Яйцо куриное С1", "Соль"] },
      { name: "Фарш тайёрлаш", process: "Смешивание", params: { time: "10" },
        ings: ["Баранина", "Лук репчатый", "Зира (кумин)", "Перец чёрный молотый", "Соль"] },
      { name: "Буғда пишириш", process: "Варка", params: { temp: "100", time: "45" },
        ings: [] },
    ]},
  { name: "Самса", category: "Ўзбек таомлари", outputUnit: "шт", outputQty: 20,
    steps: [
      { name: "Хамир тайёрлаш", process: "Смешивание", params: { time: "15" },
        ings: ["Мука пшеничная в/с", "Масло сливочное 82%", "Соль"] },
      { name: "Фарш тайёрлаш", process: "Смешивание", params: { time: "10" },
        ings: ["Баранина", "Лук репчатый", "Зира (кумин)", "Соль", "Перец чёрный молотый"] },
      { name: "Тандирда пишириш", process: "Запекание", params: { temp: "220", time: "25" },
        ings: ["Яйцо куриное С1"] },
    ]},
  { name: "Чучвара", category: "Ўзбек таомлари", outputUnit: "порц", outputQty: 8,
    steps: [
      { name: "Хамир тайёрлаш", process: "Смешивание", params: { time: "15" },
        ings: ["Мука пшеничная в/с", "Яйцо куриное С1", "Соль"] },
      { name: "Фарш тайёрлаш", process: "Смешивание", params: { time: "10" },
        ings: ["Говядина (фарш)", "Лук репчатый", "Соль", "Перец чёрный молотый"] },
      { name: "Қайнатиш", process: "Варка", params: { temp: "100", time: "15" },
        ings: [] },
    ]},

  // ── Европейские блюда ──
  { name: "Борщ", category: "Европа таомлари", outputUnit: "порц", outputQty: 10,
    steps: [
      { name: "Бульон", process: "Варка", params: { temp: "100", time: "60" },
        ings: ["Говядина (лопатка)", "Лук репчатый", "Морковь", "Лавровый лист"] },
      { name: "Зажарка", process: "Жарка", params: { temp: "160", time: "15" },
        ings: ["Масло подсолнечное", "Свёкла", "Морковь", "Лук репчатый", "Томатная паста", "Уксус 9%"] },
      { name: "Варка", process: "Варка", params: { temp: "100", time: "20" },
        ings: ["Картофель", "Капуста белокочанная", "Чеснок", "Соль", "Перец чёрный молотый"] },
    ]},
  { name: "Цезарь с курицей", category: "Европа таомлари", outputUnit: "порц", outputQty: 4,
    steps: [
      { name: "Курица", process: "Жарка", params: { temp: "200", time: "15" },
        ings: ["Куриное филе", "Масло оливковое", "Соль", "Перец чёрный молотый"] },
      { name: "Сборка", process: "Смешивание", params: { time: "5" },
        ings: ["Салат (листовой)", "Сыр пармезан", "Хлеб белый", "Яйцо куриное С1", "Майонез", "Чеснок", "Лимон"] },
    ]},
  { name: "Паста Карбонара", category: "Европа таомлари", outputUnit: "порц", outputQty: 4,
    steps: [
      { name: "Макароны", process: "Варка", params: { temp: "100", time: "10" },
        ings: ["Макароны (спагетти)", "Соль"] },
      { name: "Соус", process: "Жарка", params: { temp: "160", time: "10" },
        ings: ["Яйцо куриное С1", "Сыр пармезан", "Сливки 33%", "Перец чёрный молотый"] },
    ]},
  { name: "Пицца Маргарита", category: "Европа таомлари", outputUnit: "шт", outputQty: 2,
    steps: [
      { name: "Тесто", process: "Смешивание", params: { time: "20" },
        ings: ["Мука пшеничная в/с", "Дрожжи сухие", "Масло оливковое", "Сахар белый", "Соль"] },
      { name: "Выпечка", process: "Запекание", params: { temp: "250", time: "12" },
        ings: ["Томатная паста", "Сыр моцарелла", "Базилик (свежий)"] },
    ]},

  // ── Фаст-фуд / Стрит-фуд ──
  { name: "Бургер классический", category: "Фаст-фуд", outputUnit: "шт", outputQty: 8,
    steps: [
      { name: "Котлета", process: "Жарка", params: { temp: "200", time: "8" },
        ings: ["Говядина (фарш)", "Лук репчатый", "Соль", "Перец чёрный молотый"] },
      { name: "Сборка", process: "Смешивание", params: { time: "3" },
        ings: ["Хлеб белый", "Салат (листовой)", "Помидоры", "Огурцы", "Сыр твёрдый", "Кетчуп", "Майонез"] },
    ]},
  { name: "Шаурма (донер)", category: "Фаст-фуд", outputUnit: "шт", outputQty: 10,
    steps: [
      { name: "Мясо", process: "Жарка", params: { temp: "200", time: "15" },
        ings: ["Куриное филе", "Масло подсолнечное", "Соль", "Паприка", "Чеснок"] },
      { name: "Сборка", process: "Смешивание", params: { time: "3" },
        ings: ["Лаваш", "Помидоры", "Огурцы", "Капуста белокочанная", "Лук репчатый", "Кетчуп", "Майонез"] },
    ]},

  // ── Выпечка и десерты ──
  { name: "Блины (тонкие)", category: "Десерт ва ширинлик", outputUnit: "порц", outputQty: 10,
    steps: [
      { name: "Тесто", process: "Смешивание", params: { time: "10" },
        ings: ["Мука пшеничная в/с", "Молоко 3.2%", "Яйцо куриное С1", "Сахар белый", "Соль", "Масло подсолнечное"] },
      { name: "Выпечка", process: "Жарка", params: { temp: "180", time: "20" },
        ings: ["Масло сливочное 82%"] },
    ]},
  { name: "Чизкейк", category: "Десерт ва ширинлик", outputUnit: "порц", outputQty: 8,
    steps: [
      { name: "Основа", process: "Смешивание", params: { time: "10" },
        ings: ["Масло сливочное 82%", "Сахар белый", "Панировочные сухари"] },
      { name: "Начинка", process: "Смешивание", params: { time: "15" },
        ings: ["Творог 9%", "Сливки 33%", "Яйцо куриное С1", "Сахар белый", "Ванилин"] },
      { name: "Выпечка", process: "Запекание", params: { temp: "160", time: "50" },
        ings: [] },
    ]},
];
